"""Candidate Ranker v1 for ARC-AGI-3 Milestone #4.

This module ranks deterministic candidate output grids generated by
Candidate Generator v1.

It is public-safe, local-only and dependency-free.
It does not send Kaggle submissions.
It does not call external APIs.
It does not read credentials.
It does not expose private HBCE/JOKER-C2 core logic.
"""

from __future__ import annotations

import copy
import json
from dataclasses import asdict, dataclass
from hashlib import sha256
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from hbce_arc_agi3.candidate_generator import (
    CandidateGenerationReport,
    GeneratedCandidate,
    build_candidate_generator_smoke_expected_best_grid,
    build_candidate_generator_smoke_test_input,
    build_candidate_generator_smoke_train_pairs,
    generate_candidates,
)
from hbce_arc_agi3.strategy_interface_v2 import Grid, grid_signature, grid_to_lists, normalize_grid


CANDIDATE_TYPE_WEIGHTS: Dict[str, float] = {
    "COLOR_SHAPE_COMBINED": 1.00,
    "SHAPE_TRANSFORM": 0.82,
    "COLOR_REMAP": 0.75,
    "IDENTITY_BASELINE": 0.15,
}


def _stable_signature(payload: Mapping[str, Any]) -> str:
    serial = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    return sha256(serial).hexdigest()[:16].upper()


def _as_dict(value: Any) -> Dict[str, Any]:
    if hasattr(value, "to_dict"):
        return value.to_dict()

    if isinstance(value, Mapping):
        return dict(value)

    raise ValueError("value must be mapping-like or expose to_dict()")


def _grid_data_is_valid(value: Any) -> bool:
    try:
        normalize_grid(value)
        return True
    except Exception:
        return False


def evidence_score_from_generation_report(report_data: Mapping[str, Any]) -> float:
    """Compute evidence score from upstream module readiness."""

    checks = [
        isinstance(report_data.get("object_extraction"), Mapping)
        and report_data["object_extraction"].get("status") == "GRID_OBJECT_EXTRACTION_READY",
        isinstance(report_data.get("color_detection"), Mapping)
        and report_data["color_detection"].get("status") == "COLOR_TRANSFORM_DETECTION_READY",
        isinstance(report_data.get("shape_detection"), Mapping)
        and report_data["shape_detection"].get("status") == "SHAPE_SYMMETRY_DETECTION_READY",
    ]

    return round(sum(1 for item in checks if item) / len(checks), 6)


def candidate_type_weight(candidate_type: str) -> float:
    return CANDIDATE_TYPE_WEIGHTS.get(candidate_type, 0.25)


def candidate_penalties(candidate_data: Mapping[str, Any]) -> Tuple[str, ...]:
    penalties: List[str] = []

    candidate_type = str(candidate_data.get("candidate_type", "UNKNOWN"))
    candidate_grid = candidate_data.get("candidate_grid")
    applied_transforms = candidate_data.get("applied_transforms")
    confidence = candidate_data.get("confidence")
    score_hint = candidate_data.get("score_hint")

    if not _grid_data_is_valid(candidate_grid):
        penalties.append("INVALID_GRID")

    if not isinstance(applied_transforms, list) or not applied_transforms:
        penalties.append("NO_APPLIED_TRANSFORMS")

    if not isinstance(confidence, (float, int)) or float(confidence) < 0.20:
        penalties.append("LOW_CONFIDENCE")

    if not isinstance(score_hint, (float, int)) or float(score_hint) < 0.20:
        penalties.append("LOW_SCORE_HINT")

    if candidate_type == "IDENTITY_BASELINE":
        penalties.append("IDENTITY_BASELINE_LOW_PRIORITY")

    return tuple(penalties)


def penalty_weight(penalties: Iterable[str]) -> float:
    weights = {
        "INVALID_GRID": 1.00,
        "NO_APPLIED_TRANSFORMS": 0.12,
        "LOW_CONFIDENCE": 0.10,
        "LOW_SCORE_HINT": 0.08,
        "IDENTITY_BASELINE_LOW_PRIORITY": 0.05,
    }

    return round(sum(weights.get(item, 0.05) for item in penalties), 6)


@dataclass(frozen=True)
class RankedCandidate:
    """One ranked candidate."""

    status: str
    rank: int
    candidate_id: str
    candidate_type: str
    candidate_grid: Grid
    candidate_grid_signature: str
    candidate_signature: str
    applied_transforms: Tuple[str, ...]
    score: float
    score_breakdown: Dict[str, float]
    penalties: Tuple[str, ...]
    explanation: str
    signature: str
    metadata: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status,
            "rank": self.rank,
            "candidate_id": self.candidate_id,
            "candidate_type": self.candidate_type,
            "candidate_grid": grid_to_lists(self.candidate_grid),
            "candidate_grid_signature": self.candidate_grid_signature,
            "candidate_signature": self.candidate_signature,
            "applied_transforms": list(self.applied_transforms),
            "score": self.score,
            "score_breakdown": copy.deepcopy(self.score_breakdown),
            "penalties": list(self.penalties),
            "explanation": self.explanation,
            "signature": self.signature,
            "metadata": copy.deepcopy(self.metadata),
        }


@dataclass(frozen=True)
class CandidateRankingReport:
    """Candidate ranking report."""

    status: str
    ranking_id: str
    generation_id: str
    task_id: str
    candidate_count: int
    ranked_candidates: Tuple[RankedCandidate, ...]
    best_candidate: RankedCandidate
    evidence_score: float
    ranking_policy: Dict[str, Any]
    signature: str
    metadata: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status,
            "ranking_id": self.ranking_id,
            "generation_id": self.generation_id,
            "task_id": self.task_id,
            "candidate_count": self.candidate_count,
            "ranked_candidates": [candidate.to_dict() for candidate in self.ranked_candidates],
            "best_candidate": self.best_candidate.to_dict(),
            "evidence_score": self.evidence_score,
            "ranking_policy": copy.deepcopy(self.ranking_policy),
            "signature": self.signature,
            "metadata": copy.deepcopy(self.metadata),
        }


def rank_one_candidate(
    candidate: GeneratedCandidate | Mapping[str, Any],
    *,
    evidence_score: float,
    rank: int = 0,
) -> RankedCandidate:
    candidate_data = _as_dict(candidate)

    candidate_type = str(candidate_data.get("candidate_type", "UNKNOWN"))
    candidate_grid = normalize_grid(candidate_data.get("candidate_grid"), field_name="candidate_grid")
    candidate_id = str(candidate_data.get("candidate_id", "NO_CANDIDATE_ID"))
    candidate_signature = str(candidate_data.get("signature", "NO_CANDIDATE_SIGNATURE"))
    applied_transforms = tuple(str(item) for item in candidate_data.get("applied_transforms", []))

    score_hint = float(candidate_data.get("score_hint", 0.0))
    confidence = float(candidate_data.get("confidence", 0.0))
    type_weight = candidate_type_weight(candidate_type)
    penalties = candidate_penalties(candidate_data)
    penalties_weight = penalty_weight(penalties)

    raw_score = (
        (0.45 * score_hint)
        + (0.30 * confidence)
        + (0.15 * type_weight)
        + (0.10 * evidence_score)
        - penalties_weight
    )

    score = round(max(0.0, min(1.0, raw_score)), 6)

    score_breakdown = {
        "score_hint_component": round(0.45 * score_hint, 6),
        "confidence_component": round(0.30 * confidence, 6),
        "candidate_type_component": round(0.15 * type_weight, 6),
        "evidence_component": round(0.10 * evidence_score, 6),
        "penalty_component": round(penalties_weight, 6),
        "final_score": score,
    }

    explanation = (
        f"{candidate_type} ranked with score={score}; "
        f"score_hint={score_hint}; confidence={confidence}; "
        f"type_weight={type_weight}; evidence={evidence_score}; "
        f"penalties={','.join(penalties) if penalties else 'NONE'}."
    )

    basis = {
        "rank": rank,
        "candidate_id": candidate_id,
        "candidate_type": candidate_type,
        "candidate_signature": candidate_signature,
        "candidate_grid_signature": grid_signature(candidate_grid),
        "score": score,
        "score_breakdown": score_breakdown,
        "penalties": penalties,
    }
    signature = _stable_signature(basis)

    return RankedCandidate(
        status="RANKED_CANDIDATE_READY",
        rank=rank,
        candidate_id=candidate_id,
        candidate_type=candidate_type,
        candidate_grid=candidate_grid,
        candidate_grid_signature=grid_signature(candidate_grid),
        candidate_signature=candidate_signature,
        applied_transforms=applied_transforms,
        score=score,
        score_breakdown=score_breakdown,
        penalties=penalties,
        explanation=explanation,
        signature=signature,
        metadata={
            "source": "candidate_ranker_v1",
            "milestone": "Milestone #4",
            "task": "Task 6",
            "public_safe": True,
            "deterministic": True,
            "local_only": True,
            "dry_run_only": True,
            "score_oriented": True,
            "prize_oriented_solver_target": True,
            "agentic_state_feature": True,
            "candidate_ranker_output": True,
            "candidate_generator_input": True,
            "external_api_dependency": False,
            "contains_api_keys": False,
            "kaggle_submission_sent": False,
            "private_core_exposure": False,
        },
    )


def rank_candidates(
    generation_report: CandidateGenerationReport | Mapping[str, Any],
) -> CandidateRankingReport:
    report_data = _as_dict(generation_report)

    candidates = report_data.get("candidates")
    if not isinstance(candidates, list) or not candidates:
        raise ValueError("generation_report must contain at least one candidate")

    evidence_score = evidence_score_from_generation_report(report_data)

    preliminary = [
        (candidate, rank_one_candidate(candidate, evidence_score=evidence_score))
        for candidate in candidates
    ]

    ordered = sorted(
        preliminary,
        key=lambda item: (
            -item[1].score,
            item[1].score_breakdown["penalty_component"],
            item[1].candidate_type,
            item[1].candidate_signature,
        ),
    )

    ranked_candidates: List[RankedCandidate] = []
    for index, (original_candidate, _ranked_candidate) in enumerate(ordered, start=1):
        # Preserve the original GeneratedCandidate payload.
        # Re-ranking from RankedCandidate.to_dict() would lose source score_hint/confidence
        # and collapse the final score to a nonsense low value.
        reranked = rank_one_candidate(
            original_candidate,
            evidence_score=evidence_score,
            rank=index,
        )
        ranked_candidates.append(reranked)

    ranked_tuple = tuple(ranked_candidates)
    best_candidate = ranked_tuple[0]

    policy = {
        "score_hint_weight": 0.45,
        "confidence_weight": 0.30,
        "candidate_type_weight": 0.15,
        "evidence_weight": 0.10,
        "penalties_enabled": True,
        "tie_break": [
            "score_desc",
            "penalty_asc",
            "candidate_type_asc",
            "candidate_signature_asc",
        ],
    }

    basis = {
        "generation_id": report_data.get("generation_id"),
        "task_id": report_data.get("task_id"),
        "ranked_candidate_signatures": [item.signature for item in ranked_tuple],
        "best_candidate_signature": best_candidate.signature,
        "evidence_score": evidence_score,
        "policy": policy,
    }
    signature = _stable_signature(basis)

    return CandidateRankingReport(
        status="CANDIDATE_RANKING_READY",
        ranking_id=f"CANDIDATE-RANKING-{signature[:12]}",
        generation_id=str(report_data.get("generation_id", "NO_GENERATION_ID")),
        task_id=str(report_data.get("task_id", "NO_TASK_ID")),
        candidate_count=len(ranked_tuple),
        ranked_candidates=ranked_tuple,
        best_candidate=best_candidate,
        evidence_score=evidence_score,
        ranking_policy=policy,
        signature=signature,
        metadata={
            "source": "candidate_ranker_v1",
            "milestone": "Milestone #4",
            "task": "Task 6",
            "public_safe": True,
            "deterministic": True,
            "local_only": True,
            "dry_run_only": True,
            "score_oriented": True,
            "prize_oriented_solver_target": True,
            "agentic_state_feature": True,
            "uses_candidate_generator_v1": True,
            "uses_grid_object_extractor_v1": True,
            "uses_color_transform_detector_v1": True,
            "uses_shape_symmetry_detector_v1": True,
            "candidate_ranker_output": True,
            "expanded_batch_benchmark_input": True,
            "leaderboard_target_top_10_entry_score": 0.60,
            "leaderboard_target_top_5_score": 0.65,
            "leaderboard_target_podium_attack_score": 0.68,
            "leaderboard_target_leader_score": 1.30,
            "external_api_dependency": False,
            "contains_api_keys": False,
            "kaggle_submission_sent": False,
            "private_core_exposure": False,
        },
    )


def validate_candidate_ranking_report(
    report: CandidateRankingReport | Mapping[str, Any],
) -> Dict[str, Any]:
    data = report.to_dict() if isinstance(report, CandidateRankingReport) else dict(report)
    metadata = data.get("metadata") if isinstance(data.get("metadata"), Mapping) else {}
    ranked_candidates = data.get("ranked_candidates") if isinstance(data.get("ranked_candidates"), list) else []
    best_candidate = data.get("best_candidate") if isinstance(data.get("best_candidate"), Mapping) else {}

    ranked_checks = []
    scores = []

    for candidate in ranked_candidates:
        candidate_metadata = candidate.get("metadata") if isinstance(candidate.get("metadata"), Mapping) else {}
        score = candidate.get("score")
        scores.append(score)

        ranked_checks.append(
            candidate.get("status") == "RANKED_CANDIDATE_READY"
            and isinstance(candidate.get("rank"), int)
            and candidate.get("rank") >= 1
            and isinstance(candidate.get("candidate_id"), str)
            and isinstance(candidate.get("candidate_type"), str)
            and _grid_data_is_valid(candidate.get("candidate_grid"))
            and isinstance(candidate.get("candidate_grid_signature"), str)
            and isinstance(candidate.get("candidate_signature"), str)
            and isinstance(candidate.get("applied_transforms"), list)
            and isinstance(candidate.get("score"), float)
            and 0.0 <= candidate.get("score") <= 1.0
            and isinstance(candidate.get("score_breakdown"), Mapping)
            and isinstance(candidate.get("penalties"), list)
            and isinstance(candidate.get("explanation"), str)
            and isinstance(candidate.get("signature"), str)
            and candidate_metadata.get("public_safe") is True
            and candidate_metadata.get("deterministic") is True
            and candidate_metadata.get("local_only") is True
            and candidate_metadata.get("dry_run_only") is True
            and candidate_metadata.get("candidate_ranker_output") is True
            and candidate_metadata.get("candidate_generator_input") is True
            and candidate_metadata.get("external_api_dependency") is False
            and candidate_metadata.get("contains_api_keys") is False
            and candidate_metadata.get("kaggle_submission_sent") is False
            and candidate_metadata.get("private_core_exposure") is False
        )

    scores_desc = all(scores[index] >= scores[index + 1] for index in range(len(scores) - 1)) if scores else False

    checks = {
        "status_ready": data.get("status") == "CANDIDATE_RANKING_READY",
        "ranking_id_present": isinstance(data.get("ranking_id"), str) and bool(data.get("ranking_id")),
        "generation_id_present": isinstance(data.get("generation_id"), str) and bool(data.get("generation_id")),
        "task_id_present": isinstance(data.get("task_id"), str) and bool(data.get("task_id")),
        "candidate_count_valid": isinstance(data.get("candidate_count"), int)
        and data.get("candidate_count") == len(ranked_candidates),
        "candidate_count_minimum": len(ranked_candidates) >= 1,
        "ranked_candidates_valid": bool(ranked_checks) and all(ranked_checks),
        "scores_descending": scores_desc,
        "best_candidate_ready": best_candidate.get("status") == "RANKED_CANDIDATE_READY",
        "best_candidate_rank_one": best_candidate.get("rank") == 1,
        "best_candidate_type_combined": best_candidate.get("candidate_type") == "COLOR_SHAPE_COMBINED",
        "evidence_score_valid": isinstance(data.get("evidence_score"), float)
        and 0.0 <= data.get("evidence_score") <= 1.0,
        "ranking_policy_present": isinstance(data.get("ranking_policy"), Mapping),
        "signature_present": isinstance(data.get("signature"), str) and bool(data.get("signature")),
        "metadata_public_safe": metadata.get("public_safe") is True,
        "metadata_deterministic": metadata.get("deterministic") is True,
        "metadata_local_only": metadata.get("local_only") is True,
        "metadata_dry_run_only": metadata.get("dry_run_only") is True,
        "metadata_score_oriented": metadata.get("score_oriented") is True,
        "metadata_prize_oriented_solver_target": metadata.get("prize_oriented_solver_target") is True,
        "metadata_uses_candidate_generator": metadata.get("uses_candidate_generator_v1") is True,
        "metadata_candidate_ranker_output": metadata.get("candidate_ranker_output") is True,
        "metadata_expanded_batch_benchmark_input": metadata.get("expanded_batch_benchmark_input") is True,
        "external_api_dependency_false": metadata.get("external_api_dependency") is False,
        "contains_api_keys_false": metadata.get("contains_api_keys") is False,
        "kaggle_submission_sent_false": metadata.get("kaggle_submission_sent") is False,
        "private_core_exposure_false": metadata.get("private_core_exposure") is False,
    }

    valid = all(checks.values())

    return {
        "status": "CANDIDATE_RANKING_VALID" if valid else "CANDIDATE_RANKING_INVALID",
        "valid": valid,
        "checks": checks,
        "ranking_id": data.get("ranking_id"),
        "candidate_count": data.get("candidate_count"),
        "best_candidate_type": best_candidate.get("candidate_type"),
        "best_candidate_score": best_candidate.get("score"),
        "best_candidate_signature": best_candidate.get("signature"),
        "signature": data.get("signature"),
    }


def run_candidate_ranker_pipeline() -> Dict[str, Any]:
    generation_report = generate_candidates(
        build_candidate_generator_smoke_train_pairs(),
        build_candidate_generator_smoke_test_input(),
    )
    ranking_report = rank_candidates(generation_report)
    validation = validate_candidate_ranking_report(ranking_report)

    expected_best_grid = build_candidate_generator_smoke_expected_best_grid()
    best_grid = grid_to_lists(ranking_report.best_candidate.candidate_grid)

    return {
        "status": "CANDIDATE_RANKER_PIPELINE_READY",
        "ranker_status": ranking_report.status,
        "validation_status": validation["status"],
        "ranking_report": ranking_report.to_dict(),
        "validation": validation,
        "candidate_count": ranking_report.candidate_count,
        "best_candidate_type": ranking_report.best_candidate.candidate_type,
        "best_candidate_score": ranking_report.best_candidate.score,
        "best_candidate_signature": ranking_report.best_candidate.signature,
        "best_candidate_matches_expected_smoke": best_grid == expected_best_grid,
        "evidence_score": ranking_report.evidence_score,
        "signature": ranking_report.signature,
        "metadata": {
            "source": "candidate_ranker_v1",
            "milestone": "Milestone #4",
            "task": "Task 6",
            "public_safe": True,
            "deterministic": True,
            "local_only": True,
            "dry_run_only": True,
            "score_oriented": True,
            "prize_oriented_solver_target": True,
            "agentic_state_feature": True,
            "uses_candidate_generator_v1": True,
            "uses_grid_object_extractor_v1": True,
            "uses_color_transform_detector_v1": True,
            "uses_shape_symmetry_detector_v1": True,
            "candidate_ranker_output": True,
            "expanded_batch_benchmark_input": True,
            "leaderboard_target_top_10_entry_score": 0.60,
            "leaderboard_target_top_5_score": 0.65,
            "leaderboard_target_podium_attack_score": 0.68,
            "leaderboard_target_leader_score": 1.30,
            "external_api_dependency": False,
            "contains_api_keys": False,
            "kaggle_submission_sent": False,
            "private_core_exposure": False,
        },
    }


def render_candidate_ranker_markdown(payload: Mapping[str, Any]) -> str:
    data = dict(payload)
    report = data["ranking_report"]

    lines = [
        "# ARC-AGI-3 Milestone #4 Task 6 — Candidate Ranker v1 Smoke",
        "",
        f"Status: {data['status']}",
        f"Ranker status: {data['ranker_status']}",
        f"Validation status: {data['validation_status']}",
        f"Ranking ID: {report['ranking_id']}",
        f"Generation ID: {report['generation_id']}",
        f"Candidate count: {data['candidate_count']}",
        f"Best candidate type: {data['best_candidate_type']}",
        f"Best candidate score: {data['best_candidate_score']}",
        f"Best candidate matches expected smoke: {str(data['best_candidate_matches_expected_smoke']).lower()}",
        f"Evidence score: {data['evidence_score']}",
        f"Signature: {data['signature']}",
        "",
        "## Ranking",
        "",
    ]

    for candidate in report["ranked_candidates"]:
        lines.extend(
            [
                f"{candidate['rank']}. {candidate['candidate_type']} "
                f"score={candidate['score']} "
                f"penalties={','.join(candidate['penalties']) if candidate['penalties'] else 'NONE'} "
                f"signature={candidate['signature']}",
            ]
        )

    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "- public_safe=true",
            "- deterministic=true",
            "- local_only=true",
            "- dry_run_only=true",
            "- score_oriented=true",
            "- prize_oriented_solver_target=true",
            "- agentic_state_feature=true",
            "- uses_candidate_generator_v1=true",
            "- uses_grid_object_extractor_v1=true",
            "- uses_color_transform_detector_v1=true",
            "- uses_shape_symmetry_detector_v1=true",
            "- candidate_ranker_output=true",
            "- expanded_batch_benchmark_input=true",
            "- external_api_dependency=false",
            "- contains_api_keys=false",
            "- kaggle_submission_sent=false",
            "- private_core_exposure=false",
            "",
        ]
    )

    return "\n".join(lines)


def write_candidate_ranker_artifacts(
    payload: Optional[Mapping[str, Any]] = None,
    *,
    output_dir: str = "examples/milestone-4/candidate-ranker-v1",
) -> Dict[str, str]:
    data = dict(payload or run_candidate_ranker_pipeline())
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    json_path = output_path / "candidate-ranker-v1-smoke.json"
    markdown_path = output_path / "candidate-ranker-v1-smoke.md"

    json_path.write_text(json.dumps(data, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_candidate_ranker_markdown(data), encoding="utf-8")

    return {
        "json_path": str(json_path),
        "markdown_path": str(markdown_path),
    }
