"""Milestone #6 Solver Improvement Before Real Submission v1.

Local-only solver improvement gate before any possible real Kaggle submission.

This module reads the final submission candidate audit and formalizes the
required solver improvement targets before any real upload can be considered.
It does not submit to Kaggle, authenticate, upload files, call external APIs,
read secrets, create upload archives, or create legal certification claims.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Dict, Mapping, Tuple


IMPROVEMENT_STATUS = "MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_READY"
PIPELINE_STATUS = "MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_PIPELINE_READY"
VALIDATION_STATUS = "MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_VALID"

BASELINE_COMMIT = "e2134e5 Add ARC AGI3 submission candidate final audit"
IMPROVEMENT_MODE = "SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_ONLY_NO_UPLOAD"
IMPROVEMENT_SCOPE = "DEFINE_MEASURABLE_SOLVER_IMPROVEMENT_TARGETS_BEFORE_MANUAL_SUBMISSION"
IMPROVEMENT_VERDICT = "SOLVER_IMPROVEMENT_REQUIRED_REAL_SUBMISSION_REMAINS_BLOCKED"
NEXT_ALLOWED_STAGE = "MILESTONE_6_REAL_SUBMISSION_READINESS_CLOSURE_AFTER_SOLVER_IMPROVEMENT"

DEFAULT_OUTPUT_DIR = "examples/milestone-6/solver-improvement-before-real-submission-v1"

FINAL_AUDIT_JSON = Path(
    "examples/milestone-6/submission-candidate-final-audit-v1/"
    "milestone-6-submission-candidate-final-audit-v1.json"
)

EXPECTED_IMPROVEMENT_TARGET_COUNT = 6

IMPROVEMENT_TARGETS: Tuple[Dict[str, Any], ...] = (
    {
        "target": "solver_candidate_quality",
        "priority": "P0",
        "reason": "Improve candidate solution quality before any real Kaggle submission decision.",
        "measurement": "Increase local solved-task count or deterministic candidate match rate on public sample tasks.",
        "required_before_submission": True,
    },
    {
        "target": "family_specific_rules",
        "priority": "P0",
        "reason": "Add or strengthen rules for task families already exposed by the benchmark pipeline.",
        "measurement": "Document per-family improvement and verify no regression in existing task-family policy.",
        "required_before_submission": True,
    },
    {
        "target": "candidate_ranker_discrimination",
        "priority": "P1",
        "reason": "Improve ranking between plausible candidates instead of merely preserving safe fallback choices.",
        "measurement": "Show ranker selects expected candidate more often on local deterministic cases.",
        "required_before_submission": True,
    },
    {
        "target": "failure_taxonomy_feedback_loop",
        "priority": "P1",
        "reason": "Convert known failure classes into actionable solver/ranker improvements.",
        "measurement": "Generate improvement items from failed cases and close at least one failure class locally.",
        "required_before_submission": True,
    },
    {
        "target": "submission_candidate_regression_guard",
        "priority": "P1",
        "reason": "Ensure any solver improvement does not break frozen candidate safety boundaries.",
        "measurement": "Full suite remains green and no upload/auth/API flags become true.",
        "required_before_submission": True,
    },
    {
        "target": "competitive_claim_control",
        "priority": "P2",
        "reason": "Prevent unsupported claims of competitiveness until local evidence improves.",
        "measurement": "Keep competitive_claim_absent=true unless evidence is generated by deterministic evaluation.",
        "required_before_submission": True,
    },
)

IMPROVEMENT_GATES: Tuple[str, ...] = (
    "final_audit_artifact_present",
    "final_audit_artifact_ready",
    "final_audit_artifact_valid",
    "final_audit_passed",
    "final_audit_locked",
    "final_audit_requires_solver_improvement",
    "final_audit_blocks_real_submission",
    "improvement_mode_valid",
    "improvement_scope_valid",
    "improvement_verdict_valid",
    "improvement_record_ready",
    "improvement_locked",
    "improvement_target_count_valid",
    "all_improvement_targets_required",
    "priority_p0_targets_present",
    "measurement_fields_present",
    "next_allowed_stage_valid",
    "competitive_claim_absent",
    "manual_upload_still_required",
    "manual_execution_not_performed",
    "real_submission_allowed_false",
    "ready_for_real_kaggle_submission_false",
    "real_submission_not_created",
    "kaggle_submission_not_sent",
    "upload_not_performed",
    "kaggle_authentication_not_performed",
    "external_api_dependency_false",
    "contains_api_keys_false",
    "private_core_exposure_false",
    "legal_certification_false",
)

IMPROVEMENT_ISSUES: Tuple[str, ...] = (
    "final_audit_artifact_missing",
    "final_audit_artifact_not_ready",
    "final_audit_artifact_invalid",
    "final_audit_not_passed",
    "final_audit_not_locked",
    "final_audit_does_not_require_solver_improvement",
    "final_audit_allows_real_submission",
    "improvement_mode_invalid",
    "improvement_scope_invalid",
    "improvement_verdict_invalid",
    "improvement_record_not_ready",
    "improvement_not_locked",
    "improvement_target_count_invalid",
    "improvement_target_not_required",
    "priority_p0_targets_missing",
    "measurement_field_missing",
    "next_allowed_stage_invalid",
    "competitive_claim_detected",
    "manual_upload_not_required",
    "manual_execution_performed",
    "real_submission_allowed_true",
    "ready_for_real_kaggle_submission_true",
    "real_submission_created",
    "kaggle_submission_already_sent",
    "upload_performed",
    "kaggle_authentication_performed",
    "external_api_dependency_detected",
    "api_keys_detected",
    "private_core_exposure_detected",
    "legal_certification_claim_detected",
)


def _stable_signature(payload: Mapping[str, Any]) -> str:
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:16].upper()


def _read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def _sha256(path: Path) -> str:
    if not path.exists():
        return "MISSING_HASH"
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _sha16(value: str) -> str:
    return value[:16].upper() if value != "MISSING_HASH" else value


def _boundary_from_final_audit(final_audit: Mapping[str, Any]) -> Dict[str, Any]:
    source = final_audit.get("boundary", {}) if isinstance(final_audit.get("boundary"), Mapping) else {}
    return {
        "public_safe": source.get("public_safe"),
        "deterministic": source.get("deterministic"),
        "local_only": source.get("local_only"),
        "dry_run_only": source.get("dry_run_only"),
        "external_api_dependency": source.get("external_api_dependency"),
        "contains_api_keys": source.get("contains_api_keys"),
        "kaggle_submission_sent": final_audit.get("kaggle_submission_sent"),
        "private_core_exposure": source.get("private_core_exposure"),
        "legal_certification": source.get("legal_certification"),
    }


def _boundary_intact(boundary: Mapping[str, Any]) -> bool:
    expected = {
        "public_safe": True,
        "deterministic": True,
        "local_only": True,
        "dry_run_only": True,
        "external_api_dependency": False,
        "contains_api_keys": False,
        "kaggle_submission_sent": False,
        "private_core_exposure": False,
        "legal_certification": False,
    }
    return all(boundary.get(key) is value for key, value in expected.items())


def _final_audit_source(final_audit: Mapping[str, Any]) -> Dict[str, Any]:
    file_hash = _sha256(FINAL_AUDIT_JSON)
    return {
        "name": "submission_candidate_final_audit",
        "path": str(FINAL_AUDIT_JSON),
        "present": FINAL_AUDIT_JSON.exists(),
        "expected_status": "MILESTONE_6_SUBMISSION_CANDIDATE_FINAL_AUDIT_READY",
        "actual_status": final_audit.get("status", "MISSING"),
        "ready": FINAL_AUDIT_JSON.exists()
        and final_audit.get("status") == "MILESTONE_6_SUBMISSION_CANDIDATE_FINAL_AUDIT_READY",
        "artifact_id": final_audit.get("audit_id", "MISSING_AUDIT_ID"),
        "sha256": file_hash,
        "sha256_16": _sha16(file_hash),
    }


def build_milestone_6_solver_improvement_before_real_submission() -> Dict[str, Any]:
    final_audit = _read_json(FINAL_AUDIT_JSON)
    boundary = _boundary_from_final_audit(final_audit)
    audit_source = _final_audit_source(final_audit)

    improvement_targets = tuple(dict(target) for target in IMPROVEMENT_TARGETS)
    priority_p0_count = sum(1 for item in improvement_targets if item.get("priority") == "P0")
    measurement_count = sum(1 for item in improvement_targets if bool(item.get("measurement")))
    required_target_count = sum(1 for item in improvement_targets if item.get("required_before_submission") is True)

    improvement_record = {
        "improvement_mode": IMPROVEMENT_MODE,
        "improvement_scope": IMPROVEMENT_SCOPE,
        "improvement_verdict": IMPROVEMENT_VERDICT,
        "next_allowed_stage": NEXT_ALLOWED_STAGE,
        "improvement_ready": True,
        "improvement_locked": True,
        "final_audit_id": final_audit.get("audit_id", "MISSING_AUDIT_ID"),
        "final_audit_ready": final_audit.get("audit_ready") is True,
        "final_audit_locked": final_audit.get("audit_locked") is True,
        "final_audit_solver_improvement_required": final_audit.get("solver_improvement_required") is True,
        "final_audit_real_submission_allowed": final_audit.get("real_submission_allowed") is True,
        "improvement_target_count": len(improvement_targets),
        "required_target_count": required_target_count,
        "priority_p0_count": priority_p0_count,
        "measurement_count": measurement_count,
        "solver_improvement_required": True,
        "solver_improvement_started": True,
        "solver_improvement_completed": False,
        "competitive_claim_absent": True,
        "manual_upload_required": True,
        "manual_execution_performed": False,
        "real_submission_allowed": False,
        "ready_for_real_kaggle_submission": False,
        "real_submission_created": False,
        "kaggle_submission_sent": False,
        "upload_performed": False,
        "kaggle_authentication_performed": False,
        "external_api_dependency": False,
        "contains_api_keys": False,
        "private_core_exposure": False,
        "legal_certification": False,
        "boundary_intact": _boundary_intact(boundary),
    }

    gate_state = {
        "final_audit_artifact_present": FINAL_AUDIT_JSON.exists(),
        "final_audit_artifact_ready": final_audit.get("status") == "MILESTONE_6_SUBMISSION_CANDIDATE_FINAL_AUDIT_READY",
        "final_audit_artifact_valid": bool(final_audit.get("audit_id")) and bool(final_audit.get("signature")),
        "final_audit_passed": final_audit.get("audit_ready") is True,
        "final_audit_locked": final_audit.get("audit_locked") is True,
        "final_audit_requires_solver_improvement": final_audit.get("solver_improvement_required") is True,
        "final_audit_blocks_real_submission": final_audit.get("real_submission_allowed") is False,
        "improvement_mode_valid": improvement_record["improvement_mode"] == IMPROVEMENT_MODE,
        "improvement_scope_valid": improvement_record["improvement_scope"] == IMPROVEMENT_SCOPE,
        "improvement_verdict_valid": improvement_record["improvement_verdict"] == IMPROVEMENT_VERDICT,
        "improvement_record_ready": improvement_record["improvement_ready"] is True,
        "improvement_locked": improvement_record["improvement_locked"] is True,
        "improvement_target_count_valid": len(improvement_targets) == EXPECTED_IMPROVEMENT_TARGET_COUNT,
        "all_improvement_targets_required": required_target_count == EXPECTED_IMPROVEMENT_TARGET_COUNT,
        "priority_p0_targets_present": priority_p0_count >= 2,
        "measurement_fields_present": measurement_count == EXPECTED_IMPROVEMENT_TARGET_COUNT,
        "next_allowed_stage_valid": improvement_record["next_allowed_stage"] == NEXT_ALLOWED_STAGE,
        "competitive_claim_absent": improvement_record["competitive_claim_absent"] is True,
        "manual_upload_still_required": improvement_record["manual_upload_required"] is True,
        "manual_execution_not_performed": improvement_record["manual_execution_performed"] is False,
        "real_submission_allowed_false": improvement_record["real_submission_allowed"] is False,
        "ready_for_real_kaggle_submission_false": improvement_record["ready_for_real_kaggle_submission"] is False,
        "real_submission_not_created": improvement_record["real_submission_created"] is False,
        "kaggle_submission_not_sent": improvement_record["kaggle_submission_sent"] is False,
        "upload_not_performed": improvement_record["upload_performed"] is False,
        "kaggle_authentication_not_performed": improvement_record["kaggle_authentication_performed"] is False,
        "external_api_dependency_false": boundary.get("external_api_dependency") is False,
        "contains_api_keys_false": boundary.get("contains_api_keys") is False,
        "private_core_exposure_false": boundary.get("private_core_exposure") is False,
        "legal_certification_false": boundary.get("legal_certification") is False,
    }

    issue_state = {
        "final_audit_artifact_missing": not gate_state["final_audit_artifact_present"],
        "final_audit_artifact_not_ready": not gate_state["final_audit_artifact_ready"],
        "final_audit_artifact_invalid": not gate_state["final_audit_artifact_valid"],
        "final_audit_not_passed": not gate_state["final_audit_passed"],
        "final_audit_not_locked": not gate_state["final_audit_locked"],
        "final_audit_does_not_require_solver_improvement": not gate_state["final_audit_requires_solver_improvement"],
        "final_audit_allows_real_submission": not gate_state["final_audit_blocks_real_submission"],
        "improvement_mode_invalid": not gate_state["improvement_mode_valid"],
        "improvement_scope_invalid": not gate_state["improvement_scope_valid"],
        "improvement_verdict_invalid": not gate_state["improvement_verdict_valid"],
        "improvement_record_not_ready": not gate_state["improvement_record_ready"],
        "improvement_not_locked": not gate_state["improvement_locked"],
        "improvement_target_count_invalid": not gate_state["improvement_target_count_valid"],
        "improvement_target_not_required": not gate_state["all_improvement_targets_required"],
        "priority_p0_targets_missing": not gate_state["priority_p0_targets_present"],
        "measurement_field_missing": not gate_state["measurement_fields_present"],
        "next_allowed_stage_invalid": not gate_state["next_allowed_stage_valid"],
        "competitive_claim_detected": not gate_state["competitive_claim_absent"],
        "manual_upload_not_required": not gate_state["manual_upload_still_required"],
        "manual_execution_performed": not gate_state["manual_execution_not_performed"],
        "real_submission_allowed_true": not gate_state["real_submission_allowed_false"],
        "ready_for_real_kaggle_submission_true": not gate_state["ready_for_real_kaggle_submission_false"],
        "real_submission_created": not gate_state["real_submission_not_created"],
        "kaggle_submission_already_sent": not gate_state["kaggle_submission_not_sent"],
        "upload_performed": not gate_state["upload_not_performed"],
        "kaggle_authentication_performed": not gate_state["kaggle_authentication_not_performed"],
        "external_api_dependency_detected": not gate_state["external_api_dependency_false"],
        "api_keys_detected": not gate_state["contains_api_keys_false"],
        "private_core_exposure_detected": not gate_state["private_core_exposure_false"],
        "legal_certification_claim_detected": not gate_state["legal_certification_false"],
    }

    gates = tuple(
        {"name": name, "passed": gate_state[name], "severity": "PASS" if gate_state[name] else "BLOCKING"}
        for name in IMPROVEMENT_GATES
    )
    issues = tuple(
        {"name": name, "active": issue_state[name], "severity": "BLOCKING"}
        for name in IMPROVEMENT_ISSUES
    )

    passed_gate_count = sum(1 for item in gates if item["passed"] is True)
    issue_count = sum(1 for item in issues if item["active"] is True)

    improvement_ready = (
        audit_source["ready"] is True
        and len(improvement_targets) == EXPECTED_IMPROVEMENT_TARGET_COUNT
        and required_target_count == EXPECTED_IMPROVEMENT_TARGET_COUNT
        and passed_gate_count == len(IMPROVEMENT_GATES)
        and issue_count == 0
        and _boundary_intact(boundary)
    )

    index = {
        "milestone": "Milestone #6",
        "task": "Task 9",
        "improvement_mode": IMPROVEMENT_MODE,
        "improvement_scope": IMPROVEMENT_SCOPE,
        "improvement_verdict": IMPROVEMENT_VERDICT,
        "baseline_commit": BASELINE_COMMIT,
        "depends_on_final_audit": final_audit.get("audit_id", "MISSING_AUDIT_ID"),
        "improvement_ready": improvement_ready,
        "improvement_locked": True,
        "solver_improvement_required": True,
        "solver_improvement_started": True,
        "solver_improvement_completed": False,
        "improvement_target_count": len(improvement_targets),
        "required_target_count": required_target_count,
        "priority_p0_count": priority_p0_count,
        "measurement_count": measurement_count,
        "competitive_claim_absent": True,
        "manual_upload_required": True,
        "manual_execution_performed": False,
        "real_submission_allowed": False,
        "ready_for_real_kaggle_submission": False,
        "real_submission_created": False,
        "kaggle_submission_sent": False,
        "upload_performed": False,
        "kaggle_authentication_performed": False,
        "external_api_dependency": False,
        "private_core_exposure": False,
        "legal_certification": False,
    }

    base = {
        "status": IMPROVEMENT_STATUS,
        "milestone": "Milestone #6",
        "task": "Task 9",
        "title": "Solver Improvement Before Real Submission v1",
        "baseline_commit": BASELINE_COMMIT,
        "improvement_mode": IMPROVEMENT_MODE,
        "improvement_scope": IMPROVEMENT_SCOPE,
        "improvement_verdict": IMPROVEMENT_VERDICT,
        "next_allowed_stage": NEXT_ALLOWED_STAGE,
        "final_audit_source": audit_source,
        "improvement_record": improvement_record,
        "improvement_targets": list(improvement_targets),
        "improvement_gates": list(gates),
        "improvement_issues": list(issues),
        "improvement_index": index,
        "boundary": boundary,
        "improvement_target_count": len(improvement_targets),
        "required_target_count": required_target_count,
        "priority_p0_count": priority_p0_count,
        "measurement_count": measurement_count,
        "improvement_gate_count": len(IMPROVEMENT_GATES),
        "passed_gate_count": passed_gate_count,
        "improvement_issue_count": issue_count,
        "warning_count": 0,
        "improvement_ready": improvement_ready,
        "improvement_locked": True,
        "solver_improvement_required": True,
        "solver_improvement_started": True,
        "solver_improvement_completed": False,
        "competitive_claim_absent": True,
        "manual_upload_required": True,
        "manual_execution_performed": False,
        "real_submission_allowed": False,
        "ready_for_real_kaggle_submission": False,
        "real_submission_created": False,
        "kaggle_submission_sent": False,
        "upload_performed": False,
        "kaggle_authentication_performed": False,
        "metadata": {
            "source": "milestone_6_solver_improvement_before_real_submission_v1",
            "public_safe": True,
            "deterministic": True,
            "local_only": True,
            "dry_run_only": True,
            "external_api_dependency": False,
            "contains_api_keys": False,
            "kaggle_submission_sent": False,
            "private_core_exposure": False,
            "legal_certification": False,
        },
    }

    signature = _stable_signature(base)
    return {
        **base,
        "improvement_id": f"MILESTONE-6-SOLVER-IMPROVEMENT-{signature[:12]}",
        "signature": signature,
    }


def validate_milestone_6_solver_improvement_before_real_submission(improvement: Mapping[str, Any]) -> Dict[str, Any]:
    boundary = improvement.get("boundary", {})
    gates = improvement.get("improvement_gates", [])
    issues = improvement.get("improvement_issues", [])
    targets = improvement.get("improvement_targets", [])
    source = improvement.get("final_audit_source", {})

    checks = {
        "status_ready": improvement.get("status") == IMPROVEMENT_STATUS,
        "improvement_id_present": isinstance(improvement.get("improvement_id"), str) and bool(improvement.get("improvement_id")),
        "signature_present": isinstance(improvement.get("signature"), str) and bool(improvement.get("signature")),
        "baseline_commit_valid": str(improvement.get("baseline_commit", "")).startswith("e2134e5"),
        "improvement_mode_valid": improvement.get("improvement_mode") == IMPROVEMENT_MODE,
        "improvement_scope_valid": improvement.get("improvement_scope") == IMPROVEMENT_SCOPE,
        "improvement_verdict_valid": improvement.get("improvement_verdict") == IMPROVEMENT_VERDICT,
        "final_audit_source_ready": source.get("ready") is True,
        "final_audit_hash_present": source.get("sha256") != "MISSING_HASH",
        "improvement_target_count_valid": improvement.get("improvement_target_count") == EXPECTED_IMPROVEMENT_TARGET_COUNT,
        "required_target_count_valid": improvement.get("required_target_count") == EXPECTED_IMPROVEMENT_TARGET_COUNT,
        "priority_p0_count_valid": improvement.get("priority_p0_count", 0) >= 2,
        "measurement_count_valid": improvement.get("measurement_count") == EXPECTED_IMPROVEMENT_TARGET_COUNT,
        "all_targets_required": bool(targets) and all(item.get("required_before_submission") is True for item in targets),
        "all_targets_measurable": bool(targets) and all(bool(item.get("measurement")) for item in targets),
        "improvement_gate_count_matches": improvement.get("improvement_gate_count") == len(IMPROVEMENT_GATES),
        "all_improvement_gates_passed": bool(gates) and all(item.get("passed") is True for item in gates),
        "improvement_issue_count_zero": improvement.get("improvement_issue_count") == 0,
        "all_improvement_issues_inactive": bool(issues) and all(item.get("active") is False for item in issues),
        "improvement_ready": improvement.get("improvement_ready") is True,
        "improvement_locked": improvement.get("improvement_locked") is True,
        "solver_improvement_required": improvement.get("solver_improvement_required") is True,
        "solver_improvement_started": improvement.get("solver_improvement_started") is True,
        "solver_improvement_not_completed": improvement.get("solver_improvement_completed") is False,
        "competitive_claim_absent": improvement.get("competitive_claim_absent") is True,
        "manual_upload_required": improvement.get("manual_upload_required") is True,
        "manual_execution_not_performed": improvement.get("manual_execution_performed") is False,
        "real_submission_allowed_false": improvement.get("real_submission_allowed") is False,
        "ready_for_real_kaggle_submission_false": improvement.get("ready_for_real_kaggle_submission") is False,
        "real_submission_not_created": improvement.get("real_submission_created") is False,
        "kaggle_submission_not_sent": improvement.get("kaggle_submission_sent") is False,
        "upload_not_performed": improvement.get("upload_performed") is False,
        "kaggle_authentication_not_performed": improvement.get("kaggle_authentication_performed") is False,
        "public_safe": boundary.get("public_safe") is True,
        "deterministic": boundary.get("deterministic") is True,
        "local_only": boundary.get("local_only") is True,
        "dry_run_only": boundary.get("dry_run_only") is True,
        "external_api_dependency_false": boundary.get("external_api_dependency") is False,
        "contains_api_keys_false": boundary.get("contains_api_keys") is False,
        "private_core_exposure_false": boundary.get("private_core_exposure") is False,
        "legal_certification_false": boundary.get("legal_certification") is False,
    }

    valid = all(checks.values())
    return {
        "status": VALIDATION_STATUS if valid else "MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_INVALID",
        "valid": valid,
        "checks": checks,
        "improvement_id": improvement.get("improvement_id"),
        "signature": improvement.get("signature"),
    }


def render_solver_improvement_before_real_submission_markdown(improvement: Mapping[str, Any]) -> str:
    lines = [
        "# ARC AGI3 Milestone #6 - Solver Improvement Before Real Submission v1",
        "",
        f"- status: {improvement['status']}",
        f"- improvement_id: {improvement['improvement_id']}",
        f"- signature: {improvement['signature']}",
        f"- baseline_commit: {improvement['baseline_commit']}",
        f"- improvement_mode: {improvement['improvement_mode']}",
        f"- improvement_scope: {improvement['improvement_scope']}",
        f"- improvement_verdict: {improvement['improvement_verdict']}",
        f"- improvement_target_count: {improvement['improvement_target_count']}",
        f"- required_target_count: {improvement['required_target_count']}",
        f"- priority_p0_count: {improvement['priority_p0_count']}",
        f"- measurement_count: {improvement['measurement_count']}",
        f"- improvement_gate_count: {improvement['improvement_gate_count']}",
        f"- passed_gate_count: {improvement['passed_gate_count']}",
        f"- improvement_issue_count: {improvement['improvement_issue_count']}",
        f"- improvement_ready: {improvement['improvement_ready']}",
        f"- improvement_locked: {improvement['improvement_locked']}",
        f"- solver_improvement_required: {improvement['solver_improvement_required']}",
        f"- solver_improvement_started: {improvement['solver_improvement_started']}",
        f"- solver_improvement_completed: {improvement['solver_improvement_completed']}",
        f"- real_submission_allowed: {improvement['real_submission_allowed']}",
        f"- kaggle_submission_sent: {improvement['kaggle_submission_sent']}",
        f"- upload_performed: {improvement['upload_performed']}",
        "",
        "## Improvement targets",
        "",
    ]

    for target in improvement["improvement_targets"]:
        lines.append(
            f"- {target['priority']} {target['target']}: required={target['required_before_submission']} "
            f"measurement={target['measurement']}"
        )

    lines.extend(
        [
            "",
            "## Decision",
            "",
            "Real submission remains blocked. Solver improvement is required before any manual upload decision.",
            "",
            "## Markers",
            "",
            "ARC_AGI3_MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_V1_READY=true",
            "ARC_AGI3_MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_VALID=true",
            "ARC_AGI3_MILESTONE_6_IMPROVEMENT_MODE=SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_ONLY_NO_UPLOAD",
            "ARC_AGI3_MILESTONE_6_IMPROVEMENT_VERDICT=SOLVER_IMPROVEMENT_REQUIRED_REAL_SUBMISSION_REMAINS_BLOCKED",
            "ARC_AGI3_MILESTONE_6_IMPROVEMENT_READY=true",
            "ARC_AGI3_MILESTONE_6_IMPROVEMENT_LOCKED=true",
            "ARC_AGI3_MILESTONE_6_SOLVER_IMPROVEMENT_REQUIRED=true",
            "ARC_AGI3_MILESTONE_6_SOLVER_IMPROVEMENT_STARTED=true",
            "ARC_AGI3_MILESTONE_6_SOLVER_IMPROVEMENT_COMPLETED=false",
            "ARC_AGI3_MILESTONE_6_IMPROVEMENT_TARGET_COUNT=6",
            "ARC_AGI3_MILESTONE_6_COMPETITIVE_CLAIM_ABSENT=true",
            "ARC_AGI3_MILESTONE_6_REAL_SUBMISSION_ALLOWED=false",
            "ARC_AGI3_MILESTONE_6_READY_FOR_REAL_KAGGLE_SUBMISSION=false",
            "ARC_AGI3_MILESTONE_6_REAL_SUBMISSION_CREATED=false",
            "ARC_AGI3_MILESTONE_6_UPLOAD_PERFORMED=false",
            "ARC_AGI3_MILESTONE_6_KAGGLE_AUTHENTICATION_PERFORMED=false",
            "ARC_AGI3_MILESTONE_6_BASELINE_FINAL_AUDIT_COMMIT=e2134e5",
            "ARC_AGI3_KAGGLE_SUBMISSION_SENT=false",
            "ARC_AGI3_EXTERNAL_API_DEPENDENCY=false",
            "ARC_AGI3_PRIVATE_CORE_EXPOSURE=false",
            "ARC_AGI3_LEGAL_CERTIFICATION=false",
            "",
        ]
    )

    return "\n".join(lines)


def render_solver_improvement_before_real_submission_manifest(improvement: Mapping[str, Any]) -> str:
    lines = [
        "ARC AGI3 MILESTONE 6 SOLVER IMPROVEMENT BEFORE REAL SUBMISSION MANIFEST v1",
        f"improvement_id={improvement['improvement_id']}",
        f"signature={improvement['signature']}",
        f"status={improvement['status']}",
        f"baseline_commit={improvement['baseline_commit']}",
        f"improvement_mode={improvement['improvement_mode']}",
        f"improvement_verdict={improvement['improvement_verdict']}",
        f"improvement_target_count={improvement['improvement_target_count']}",
        f"required_target_count={improvement['required_target_count']}",
        f"priority_p0_count={improvement['priority_p0_count']}",
        f"measurement_count={improvement['measurement_count']}",
        f"improvement_gate_count={improvement['improvement_gate_count']}",
        f"passed_gate_count={improvement['passed_gate_count']}",
        f"improvement_issue_count={improvement['improvement_issue_count']}",
        f"improvement_ready={improvement['improvement_ready']}",
        f"improvement_locked={improvement['improvement_locked']}",
        f"solver_improvement_required={improvement['solver_improvement_required']}",
        f"solver_improvement_started={improvement['solver_improvement_started']}",
        f"solver_improvement_completed={improvement['solver_improvement_completed']}",
        f"competitive_claim_absent={improvement['competitive_claim_absent']}",
        f"manual_upload_required={improvement['manual_upload_required']}",
        f"manual_execution_performed={improvement['manual_execution_performed']}",
        f"real_submission_allowed={improvement['real_submission_allowed']}",
        f"ready_for_real_kaggle_submission={improvement['ready_for_real_kaggle_submission']}",
        f"real_submission_created={improvement['real_submission_created']}",
        f"kaggle_submission_sent={improvement['kaggle_submission_sent']}",
        f"upload_performed={improvement['upload_performed']}",
        f"kaggle_authentication_performed={improvement['kaggle_authentication_performed']}",
        "external_api_dependency=false",
        "contains_api_keys=false",
        "private_core_exposure=false",
        "legal_certification=false",
        "",
        "IMPROVEMENT_TARGETS",
    ]

    for target in improvement["improvement_targets"]:
        lines.append(
            f"{target['priority']} {target['target']} required={target['required_before_submission']} "
            f"measurement={target['measurement']}"
        )

    lines.append("")
    return "\n".join(lines)


def write_solver_improvement_before_real_submission_artifacts(
    improvement: Mapping[str, Any] | None = None,
    *,
    output_dir: str = DEFAULT_OUTPUT_DIR,
) -> Dict[str, str]:
    improvement = dict(improvement or build_milestone_6_solver_improvement_before_real_submission())
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    json_path = output / "milestone-6-solver-improvement-before-real-submission-v1.json"
    md_path = output / "milestone-6-solver-improvement-before-real-submission-v1.md"
    manifest_path = output / "milestone-6-solver-improvement-before-real-submission-manifest-v1.txt"
    index_path = output / "milestone-6-solver-improvement-before-real-submission-index-v1.json"

    json_path.write_text(json.dumps(improvement, indent=2, sort_keys=True), encoding="utf-8")
    md_path.write_text(render_solver_improvement_before_real_submission_markdown(improvement), encoding="utf-8")
    manifest_path.write_text(render_solver_improvement_before_real_submission_manifest(improvement), encoding="utf-8")
    index_path.write_text(json.dumps(improvement["improvement_index"], indent=2, sort_keys=True), encoding="utf-8")

    return {
        "json_path": str(json_path),
        "markdown_path": str(md_path),
        "manifest_path": str(manifest_path),
        "index_path": str(index_path),
    }


def run_milestone_6_solver_improvement_before_real_submission_pipeline() -> Dict[str, Any]:
    improvement = build_milestone_6_solver_improvement_before_real_submission()
    validation = validate_milestone_6_solver_improvement_before_real_submission(improvement)
    artifacts = write_solver_improvement_before_real_submission_artifacts(improvement)

    return {
        "status": PIPELINE_STATUS if validation["valid"] else "MILESTONE_6_SOLVER_IMPROVEMENT_BEFORE_REAL_SUBMISSION_PIPELINE_INVALID",
        "improvement_status": improvement["status"],
        "validation_status": validation["status"],
        "improvement": improvement,
        "improvement_id": improvement["improvement_id"],
        "signature": improvement["signature"],
        "improvement_mode": improvement["improvement_mode"],
        "improvement_verdict": improvement["improvement_verdict"],
        "improvement_target_count": improvement["improvement_target_count"],
        "required_target_count": improvement["required_target_count"],
        "priority_p0_count": improvement["priority_p0_count"],
        "measurement_count": improvement["measurement_count"],
        "improvement_gate_count": improvement["improvement_gate_count"],
        "passed_gate_count": improvement["passed_gate_count"],
        "improvement_issue_count": improvement["improvement_issue_count"],
        "warning_count": improvement["warning_count"],
        "improvement_ready": improvement["improvement_ready"],
        "improvement_locked": improvement["improvement_locked"],
        "solver_improvement_required": improvement["solver_improvement_required"],
        "solver_improvement_started": improvement["solver_improvement_started"],
        "solver_improvement_completed": improvement["solver_improvement_completed"],
        "competitive_claim_absent": improvement["competitive_claim_absent"],
        "manual_upload_required": improvement["manual_upload_required"],
        "manual_execution_performed": improvement["manual_execution_performed"],
        "real_submission_allowed": improvement["real_submission_allowed"],
        "ready_for_real_kaggle_submission": improvement["ready_for_real_kaggle_submission"],
        "real_submission_created": improvement["real_submission_created"],
        "kaggle_submission_sent": improvement["kaggle_submission_sent"],
        "upload_performed": improvement["upload_performed"],
        "kaggle_authentication_performed": improvement["kaggle_authentication_performed"],
        "artifacts": artifacts,
        "metadata": improvement["metadata"],
    }
