from hbce_arc_agi3.milestone_9_real_submission_blocked_closure import (
    run_milestone_9_real_submission_blocked_closure_pipeline,
)


def main() -> None:
    payload = run_milestone_9_real_submission_blocked_closure_pipeline()
    closure = payload["closure"]

    print(payload["status"])
    print(payload["closure_status"])
    print(payload["validation_status"])
    print(payload["closure_id"])
    print(payload["signature"])
    print(closure["baseline_commit"])
    print(payload["closure_mode"])
    print(payload["closure_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["closure_ready"])
    print(payload["closure_locked"])
    print(payload["real_submission_blocked_closure_created"])
    print(payload["real_submission_blocked_closure_ready"])
    print(payload["real_submission_blocked_closure_locked"])
    print(payload["milestone_9_closed"])
    print(payload["milestone_9_closure_type"])
    print(payload["milestone_9_closure_reason"])
    print(payload["milestone_9_closure_verdict"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_decision_reason"])
    print(payload["required_declaration_count"])
    print(payload["provided_declaration_count"])
    print(payload["accepted_declaration_count"])
    print(payload["explicit_operator_approval_phrase_received"])
    print(payload["closure_check_count"])
    print(payload["closure_case_count"])
    print(payload["closure_pass_count"])
    print(payload["closure_failure_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["closure_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["closure_issue_count"])
    print(payload["warning_count"])
    print(payload["operator_approval_required"])
    print(payload["operator_approval_granted"])
    print(payload["operator_approval_received"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(closure["closure_source_summary"]["decision_id"])
    print(closure["closure_source_summary"]["candidate_id"])
    print(closure["closure_source_summary"]["candidate_signature"])
    print(all(result["passed"] for result in closure["closure_results"]))
    print(all(item["passed"] for item in closure["closure_gates"]))
    print(all(item["active"] is False for item in closure["closure_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
