from hbce_arc_agi3.milestone_7_local_score_improvement_report import (
    run_milestone_7_local_score_improvement_report_pipeline,
)


def main() -> None:
    payload = run_milestone_7_local_score_improvement_report_pipeline()
    report = payload["report"]

    print(payload["status"])
    print(payload["report_status"])
    print(payload["validation_status"])
    print(payload["report_id"])
    print(payload["signature"])
    print(report["baseline_commit"])
    print(payload["report_mode"])
    print(payload["report_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["family_report_count"])
    print(payload["benchmark_case_count"])
    print(payload["local_measurement_count"])
    print(payload["improvement_signal_count"])
    print(payload["blocking_control_count"])
    print(payload["report_section_count"])
    print(payload["regression_pass_count"])
    print(payload["regression_failure_count"])
    print(payload["report_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["report_issue_count"])
    print(payload["warning_count"])
    print(payload["report_ready"])
    print(payload["report_locked"])
    print(payload["runtime_solver_modified"])
    print(payload["ranker_runtime_modified"])
    print(payload["benchmark_runtime_modified"])
    print(payload["report_runtime_modified"])
    print(payload["local_score_report_ready"])
    print(payload["local_score_claim_absent"])
    print(payload["competitive_score_claim_absent"])
    print(payload["public_leaderboard_claim_absent"])
    print(payload["submission_candidate_rebuild_required"])
    print(payload["solver_improvement_required"])
    print(payload["competitive_claim_absent"])
    print(payload["manual_submission_allowed"])
    print(payload["manual_upload_performed"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["real_submission_created"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(all(item["ready_for_task_8"] for item in report["family_reports"]))
    print(all(item["numeric_score_claim"] is False for item in report["local_measurements"]))
    print(all(item["passed"] for item in report["report_gates"]))
    print(all(item["active"] is False for item in report["report_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
