from hbce_arc_agi3.milestone_8_release_decision_layer import (
    run_milestone_8_release_decision_layer_pipeline,
)


def main() -> None:
    payload = run_milestone_8_release_decision_layer_pipeline()
    decision = payload["decision"]

    print(payload["status"])
    print(payload["decision_status"])
    print(payload["validation_status"])
    print(payload["decision_id"])
    print(payload["signature"])
    print(decision["baseline_commit"])
    print(payload["decision_mode"])
    print(payload["decision_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["closed_task_count"])
    print(payload["source_commit_count"])
    print(payload["decision_case_count"])
    print(payload["decision_pass_count"])
    print(payload["decision_failure_count"])
    print(payload["required_declaration_count"])
    print(payload["provided_declaration_count"])
    print(payload["accepted_declaration_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["decision_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["decision_issue_count"])
    print(payload["warning_count"])
    print(payload["decision_ready"])
    print(payload["decision_locked"])
    print(payload["package_ready_for_manual_review"])
    print(payload["operator_approval_required"])
    print(payload["operator_approval_granted"])
    print(payload["operator_approval_received"])
    print(payload["release_decision_layer_created"])
    print(payload["manual_review_package_ready"])
    print(payload["final_package_verified"])
    print(payload["approval_contract_ready"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(all(result["passed"] for result in decision["decision_results"]))
    print(all(item["passed"] for item in decision["decision_gates"]))
    print(all(item["active"] is False for item in decision["decision_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
