from hbce_arc_agi3.milestone_9_real_submission_preflight_gate import (
    run_milestone_9_real_submission_preflight_gate_pipeline,
)


def main() -> None:
    payload = run_milestone_9_real_submission_preflight_gate_pipeline()
    preflight = payload["preflight"]

    print(payload["status"])
    print(payload["preflight_status"])
    print(payload["validation_status"])
    print(payload["preflight_id"])
    print(payload["signature"])
    print(preflight["baseline_commit"])
    print(payload["preflight_mode"])
    print(payload["preflight_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["preflight_ready"])
    print(payload["preflight_locked"])
    print(payload["real_submission_preflight_created"])
    print(payload["real_submission_preflight_ready"])
    print(payload["real_submission_preflight_completed"])
    print(payload["preflight_gate_ready"])
    print(payload["preflight_gate_open"])
    print(payload["candidate_count"])
    print(payload["preflight_check_count"])
    print(payload["preflight_case_count"])
    print(payload["preflight_pass_count"])
    print(payload["preflight_failure_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["preflight_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["preflight_issue_count"])
    print(payload["warning_count"])
    print(payload["operator_approval_required"])
    print(payload["operator_approval_granted"])
    print(payload["operator_approval_received"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(preflight["preflight_source_summary"]["candidate_source_path"])
    print(preflight["preflight_source_summary"]["candidate_id"])
    print(preflight["preflight_source_summary"]["candidate_signature"])
    print(all(result["passed"] for result in preflight["preflight_results"]))
    print(all(item["passed"] for item in preflight["preflight_gates"]))
    print(all(item["active"] is False for item in preflight["preflight_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
