from hbce_arc_agi3.milestone_9_local_candidate_manual_review import (
    run_milestone_9_local_candidate_manual_review_pipeline,
)


def main() -> None:
    payload = run_milestone_9_local_candidate_manual_review_pipeline()
    review = payload["review"]

    print(payload["status"])
    print(payload["review_status"])
    print(payload["validation_status"])
    print(payload["review_id"])
    print(payload["signature"])
    print(review["baseline_commit"])
    print(payload["review_mode"])
    print(payload["review_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["review_ready"])
    print(payload["review_locked"])
    print(payload["local_candidate_manual_review_created"])
    print(payload["local_candidate_manual_review_ready"])
    print(payload["local_candidate_manual_review_completed"])
    print(payload["candidate_count"])
    print(payload["review_check_count"])
    print(payload["review_case_count"])
    print(payload["review_pass_count"])
    print(payload["review_failure_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["review_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["review_issue_count"])
    print(payload["warning_count"])
    print(payload["operator_approval_required"])
    print(payload["operator_approval_granted"])
    print(payload["operator_approval_received"])
    print(payload["manual_upload_allowed"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(review["candidate_source"]["path"])
    print(review["candidate_source"]["candidate_id"])
    print(review["candidate_source"]["signature"])
    print(all(result["passed"] for result in review["review_results"]))
    print(all(item["passed"] for item in review["review_gates"]))
    print(all(item["active"] is False for item in review["review_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
