from hbce_arc_agi3.milestone_11_public_game_inventory_baseline_run import (
    run_milestone_11_public_game_inventory_baseline_run_pipeline,
)


def main() -> None:
    payload = run_milestone_11_public_game_inventory_baseline_run_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_2_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_2_ready"])
    print(payload["inventory_created"])
    print(payload["inventory_scan_completed"])
    print(payload["compatible_fixture_detection_completed"])
    print(payload["candidate_path_count"])
    print(payload["total_file_count"])
    print(payload["compatible_fixture_count"])
    print(payload["has_local_public_fixtures"])
    print(payload["baseline_policy_created"])
    print(payload["baseline_attempt_recorded"])
    print(payload["baseline_result_recorded"])
    print(payload["baseline_execution_performed"])
    print(payload["baseline_execution_mode"])
    print(payload["baseline_status"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["inventory_check_count"])
    print(payload["inventory_case_count"])
    print(payload["inventory_pass_count"])
    print(payload["inventory_failure_count"])
    print(payload["inventory_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["inventory_issue_count"])
    print(payload["warning_count"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["m11_opening_id"])
    print(record["source_summary"]["selected_candidate_id"])
    print(record["source_summary"]["candidate_package_id"])
    print(record["source_summary"]["rebuilt_candidate_id"])
    print(all(result["passed"] for result in record["inventory_results"]))
    print(all(item["passed"] for item in record["inventory_gates"]))
    print(all(item["active"] is False for item in record["inventory_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["inventory_path"])
    print(payload["artifacts"]["baseline_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
