from hbce_arc_agi3.milestone_9_operator_approval_gate import (
    run_milestone_9_operator_approval_gate_pipeline,
)


def main() -> None:
    payload = run_milestone_9_operator_approval_gate_pipeline()
    approval = payload["approval"]

    print(payload["status"])
    print(payload["approval_status"])
    print(payload["validation_status"])
    print(payload["approval_id"])
    print(payload["signature"])
    print(approval["baseline_commit"])
    print(payload["approval_mode"])
    print(payload["approval_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["approval_ready"])
    print(payload["approval_locked"])
    print(payload["operator_approval_gate_created"])
    print(payload["operator_approval_gate_ready"])
    print(payload["operator_approval_gate_open"])
    print(payload["required_declaration_count"])
    print(payload["provided_declaration_count"])
    print(payload["accepted_declaration_count"])
    print(payload["explicit_operator_approval_phrase_received"])
    print(payload["approval_check_count"])
    print(payload["approval_case_count"])
    print(payload["approval_pass_count"])
    print(payload["approval_failure_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["approval_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["approval_issue_count"])
    print(payload["warning_count"])
    print(payload["operator_approval_required"])
    print(payload["operator_approval_granted"])
    print(payload["operator_approval_received"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(approval["approval_source_summary"]["candidate_source_path"])
    print(approval["approval_source_summary"]["candidate_id"])
    print(approval["approval_source_summary"]["candidate_signature"])
    print(all(result["passed"] for result in approval["approval_results"]))
    print(all(item["passed"] for item in approval["approval_gates"]))
    print(all(item["active"] is False for item in approval["approval_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
