from hbce_arc_agi3.milestone_7_ranker_evidence_upgrade import (
    run_milestone_7_ranker_evidence_upgrade_pipeline,
)


def main() -> None:
    payload = run_milestone_7_ranker_evidence_upgrade_pipeline()
    ranker = payload["ranker"]

    print(payload["status"])
    print(payload["ranker_status"])
    print(payload["validation_status"])
    print(payload["ranker_id"])
    print(payload["signature"])
    print(ranker["baseline_commit"])
    print(payload["ranker_mode"])
    print(payload["ranker_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["profile_count"])
    print(payload["source_generator_count"])
    print(payload["evidence_channel_count"])
    print(payload["scoring_rule_count"])
    print(payload["calibration_rule_count"])
    print(payload["regression_guard_count"])
    print(payload["aggregate_max_score"])
    print(payload["ranker_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["ranker_issue_count"])
    print(payload["warning_count"])
    print(payload["ranker_ready"])
    print(payload["ranker_locked"])
    print(payload["runtime_solver_modified"])
    print(payload["ranker_runtime_modified"])
    print(payload["ranker_evidence_profiles_ready"])
    print(payload["solver_improvement_required"])
    print(payload["competitive_claim_absent"])
    print(payload["manual_submission_allowed"])
    print(payload["manual_upload_performed"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["real_submission_created"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(all(item["ranker_runtime_modified"] is False for item in ranker["ranker_profiles"]))
    print(all(item["ready_for_task_6"] for item in ranker["ranker_profiles"]))
    print(all(item["max_profile_score"] == 100 for item in ranker["ranker_profiles"]))
    print(all(item["passed"] for item in ranker["ranker_gates"]))
    print(all(item["active"] is False for item in ranker["ranker_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
