from hbce_arc_agi3.milestone_9_manual_submission_governance_plan import (
    run_milestone_9_manual_submission_governance_plan_pipeline,
)


def main() -> None:
    payload = run_milestone_9_manual_submission_governance_plan_pipeline()
    plan = payload["plan"]

    print(payload["status"])
    print(payload["plan_status"])
    print(payload["validation_status"])
    print(payload["plan_id"])
    print(payload["signature"])
    print(plan["baseline_commit"])
    print(payload["plan_mode"])
    print(payload["plan_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["milestone_9_open"])
    print(payload["governance_phase_count"])
    print(payload["pre_submission_gate_count"])
    print(payload["plan_case_count"])
    print(payload["plan_pass_count"])
    print(payload["plan_failure_count"])
    print(payload["required_declaration_count"])
    print(payload["provided_declaration_count"])
    print(payload["accepted_declaration_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["plan_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["plan_issue_count"])
    print(payload["warning_count"])
    print(payload["plan_ready"])
    print(payload["plan_locked"])
    print(payload["governance_plan_created"])
    print(payload["manual_submission_governance_opened"])
    print(payload["operator_approval_contract_ready"])
    print(payload["operator_approval_required"])
    print(payload["operator_approval_granted"])
    print(payload["operator_approval_received"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(all(result["passed"] for result in plan["plan_results"]))
    print(all(item["passed"] for item in plan["plan_gates"]))
    print(all(item["active"] is False for item in plan["plan_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
