from hbce_arc_agi3.milestone_10_candidate_refresh import (
    run_milestone_10_candidate_refresh_pipeline,
)


def main() -> None:
    payload = run_milestone_10_candidate_refresh_pipeline()
    candidate = payload["candidate"]

    print(payload["status"])
    print(payload["candidate_status"])
    print(payload["validation_status"])
    print(payload["candidate_refresh_id"])
    print(payload["signature"])
    print(candidate["baseline_commit"])
    print(payload["candidate_mode"])
    print(payload["candidate_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["candidate_ready"])
    print(payload["candidate_refresh_created"])
    print(payload["candidate_refresh_ready"])
    print(payload["candidate_count"])
    print(payload["ranked_candidate_count"])
    print(payload["selected_candidate_count"])
    print(payload["selected_candidate_id"])
    print(payload["candidate_package_id"])
    print(payload["candidate_artifact_created"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["candidate_check_count"])
    print(payload["candidate_case_count"])
    print(payload["candidate_pass_count"])
    print(payload["candidate_failure_count"])
    print(payload["candidate_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["candidate_issue_count"])
    print(payload["warning_count"])
    print(payload["rebuild_gate_required_next"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(candidate["source_summary"]["refresh_id"])
    print(candidate["source_summary"]["previous_candidate_id"])
    print(candidate["source_summary"]["previous_candidate_signature"])
    print(all(result["passed"] for result in candidate["candidate_results"]))
    print(all(item["passed"] for item in candidate["candidate_gates"]))
    print(all(item["active"] is False for item in candidate["candidate_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
