from hbce_arc_agi3.milestone_11_local_solver_patch_helper_wiring_plan import (
    run_milestone_11_local_solver_patch_helper_wiring_plan_pipeline,
)


def main() -> None:
    payload = run_milestone_11_local_solver_patch_helper_wiring_plan_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_12_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_12_ready"])
    print(payload["wiring_plan_ready"])
    print(payload["wiring_performed"])
    print(payload["next_stage_authorized_scope"])
    print(payload["wiring_target_count"])
    print(payload["adapter_plan_count"])
    print(payload["wiring_step_count"])
    print(payload["wiring_gate_count"])
    print(payload["stop_condition_count"])
    print(payload["required_test_count"])
    print(payload["runtime_solver_modified"])
    print(payload["ranker_runtime_modified"])
    print(payload["external_solver_dependency"])
    print(payload["diagnostic_only"])
    print(payload["kaggle_score_semantics"])
    print(payload["official_score_claim_allowed"])
    print(payload["competitive_score_claim_allowed"])
    print(payload["wiring_check_count"])
    print(payload["wiring_case_count"])
    print(payload["wiring_case_pass_count"])
    print(payload["wiring_case_failure_count"])
    print(payload["wiring_internal_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["wiring_issue_count"])
    print(payload["warning_count"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["task_11_id"])
    print(all(result["passed"] for result in record["wiring_case_results"]))
    print(all(item["passed"] for item in record["wiring_gates"]))
    print(all(item["active"] is False for item in record["wiring_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["targets_path"])
    print(payload["artifacts"]["adapters_path"])
    print(payload["artifacts"]["steps_path"])
    print(payload["artifacts"]["gates_path"])
    print(payload["artifacts"]["stops_path"])
    print(payload["artifacts"]["tests_path"])
    print(payload["artifacts"]["decision_path"])
    print(payload["artifacts"]["scorecard_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
