from hbce_arc_agi3.milestone_10_submission_preparation_closure import (
    run_milestone_10_submission_preparation_closure_pipeline,
)


def main() -> None:
    payload = run_milestone_10_submission_preparation_closure_pipeline()
    closure = payload["closure"]

    print(payload["status"])
    print(payload["closure_status"])
    print(payload["validation_status"])
    print(payload["submission_preparation_closure_id"])
    print(payload["signature"])
    print(closure["baseline_commit"])
    print(payload["closure_mode"])
    print(payload["closure_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["submission_preparation_closure_ready"])
    print(payload["submission_preparation_closure_created"])
    print(payload["submission_preparation_closure_passed"])
    print(payload["closure_scorecard_created"])
    print(payload["closure_scorecard_passed"])
    print(payload["closure_criterion_count"])
    print(payload["selected_candidate_id"])
    print(payload["candidate_package_id"])
    print(payload["rebuilt_candidate_id"])
    print(payload["rebuilt_candidate_review_id"])
    print(payload["closure_check_count"])
    print(payload["closure_case_count"])
    print(payload["closure_pass_count"])
    print(payload["closure_failure_count"])
    print(payload["closure_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["closure_issue_count"])
    print(payload["warning_count"])
    print(payload["milestone_10_closed"])
    print(payload["local_package_prepared"])
    print(payload["local_package_frozen"])
    print(payload["integrity_verified"])
    print(payload["final_audit_passed"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(closure["source_summary"]["rebuilt_candidate_review_id"])
    print(closure["source_summary"]["source_submission_candidate_rebuild_id"])
    print(closure["source_summary"]["source_rebuild_gate_id"])
    print(closure["source_summary"]["source_candidate_refresh_id"])
    print(all(result["passed"] for result in closure["closure_results"]))
    print(all(item["passed"] for item in closure["closure_gates"]))
    print(all(item["active"] is False for item in closure["closure_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["scorecard_path"])
    print(payload["artifacts"]["report_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
