from hbce_arc_agi3.milestone_11_local_diagnostic_fixture_harness import (
    run_milestone_11_local_diagnostic_fixture_harness_pipeline,
)


def main() -> None:
    payload = run_milestone_11_local_diagnostic_fixture_harness_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_5_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_5_ready"])
    print(payload["fixture_schema_created"])
    print(payload["fixture_count"])
    print(payload["valid_fixture_count"])
    print(payload["episode_runner_created"])
    print(payload["episode_count"])
    print(payload["trace_record_count"])
    print(payload["diagnostic_result_guard_active"])
    print(payload["diagnostic_only"])
    print(payload["official_score_claim_allowed"])
    print(payload["synthetic_fixture_score_claim_allowed"])
    print(payload["public_score_claim_allowed"])
    print(payload["private_score_claim_allowed"])
    print(payload["primary_condition"])
    print(payload["primary_classification"])
    print(payload["solver_failure_detected"])
    print(payload["solver_not_measured"])
    print(payload["harness_check_count"])
    print(payload["harness_case_count"])
    print(payload["harness_pass_count"])
    print(payload["harness_failure_count"])
    print(payload["harness_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["harness_issue_count"])
    print(payload["warning_count"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["task_4_id"])
    print(all(result["passed"] for result in record["harness_results"]))
    print(all(item["passed"] for item in record["harness_gates"]))
    print(all(item["active"] is False for item in record["harness_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["schema_path"])
    print(payload["artifacts"]["fixtures_path"])
    print(payload["artifacts"]["episodes_path"])
    print(payload["artifacts"]["traces_path"])
    print(payload["artifacts"]["guard_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
