from hbce_arc_agi3.milestone_10_rebuilt_candidate_review import (
    run_milestone_10_rebuilt_candidate_review_pipeline,
)


def main() -> None:
    payload = run_milestone_10_rebuilt_candidate_review_pipeline()
    review = payload["review"]

    print(payload["status"])
    print(payload["review_status"])
    print(payload["validation_status"])
    print(payload["rebuilt_candidate_review_id"])
    print(payload["signature"])
    print(review["baseline_commit"])
    print(payload["review_mode"])
    print(payload["review_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["rebuilt_candidate_review_ready"])
    print(payload["rebuilt_candidate_review_created"])
    print(payload["rebuilt_candidate_review_passed"])
    print(payload["review_scorecard_created"])
    print(payload["review_scorecard_passed"])
    print(payload["review_criterion_count"])
    print(payload["selected_candidate_id"])
    print(payload["candidate_package_id"])
    print(payload["rebuilt_candidate_id"])
    print(payload["review_check_count"])
    print(payload["review_case_count"])
    print(payload["review_pass_count"])
    print(payload["review_failure_count"])
    print(payload["review_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["review_issue_count"])
    print(payload["warning_count"])
    print(payload["submission_preparation_closure_required_next"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(review["source_summary"]["submission_candidate_rebuild_id"])
    print(review["source_summary"]["source_rebuild_gate_id"])
    print(review["source_summary"]["source_candidate_refresh_id"])
    print(all(result["passed"] for result in review["review_results"]))
    print(all(item["passed"] for item in review["review_gates"]))
    print(all(item["active"] is False for item in review["review_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["scorecard_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
