from hbce_arc_agi3.milestone_8_submission_candidate_refresh import (
    run_milestone_8_submission_candidate_refresh_pipeline,
)


def main() -> None:
    payload = run_milestone_8_submission_candidate_refresh_pipeline()
    refresh = payload["refresh"]

    print(payload["status"])
    print(payload["refresh_status"])
    print(payload["validation_status"])
    print(payload["refresh_id"])
    print(payload["signature"])
    print(payload["candidate_payload_signature"])
    print(refresh["baseline_commit"])
    print(payload["refresh_mode"])
    print(payload["refresh_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["task_count"])
    print(payload["submission_candidate_count"])
    print(payload["refresh_case_count"])
    print(payload["refresh_pass_count"])
    print(payload["refresh_failure_count"])
    print(payload["evidence_field_count"])
    print(payload["regression_guard_count"])
    print(payload["boundary_control_count"])
    print(payload["refresh_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["refresh_issue_count"])
    print(payload["warning_count"])
    print(payload["refresh_ready"])
    print(payload["refresh_locked"])
    print(payload["submission_candidate_refresh_created"])
    print(payload["local_submission_candidate_created"])
    print(payload["submission_candidate_manifest_created"])
    print(payload["submission_candidate_index_created"])
    print(payload["submission_candidate_hash_available"])
    print(payload["candidate_outputs_ranked"])
    print(payload["candidate_outputs_deduplicated"])
    print(payload["real_submission_created"])
    print(payload["real_submission_allowed"])
    print(payload["ready_for_real_kaggle_submission"])
    print(payload["kaggle_submission_sent"])
    print(payload["upload_performed"])
    print(payload["kaggle_authentication_performed"])
    print(all(result["passed"] for result in refresh["refresh_results"]))
    print(all(item["passed"] for item in refresh["refresh_gates"]))
    print(all(item["active"] is False for item in refresh["refresh_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["candidate_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
