from hbce_arc_agi3.milestone_11_public_game_failure_taxonomy import (
    run_milestone_11_public_game_failure_taxonomy_pipeline,
)


def main() -> None:
    payload = run_milestone_11_public_game_failure_taxonomy_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_3_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_3_ready"])
    print(payload["taxonomy_created"])
    print(payload["taxonomy_validated"])
    print(payload["taxonomy_class_count"])
    print(payload["active_taxonomy_class_count"])
    print(payload["next_action_count"])
    print(payload["primary_condition"])
    print(payload["primary_classification"])
    print(payload["solver_failure_detected"])
    print(payload["solver_not_measured"])
    print(payload["dataset_missing"])
    print(payload["fixture_missing"])
    print(payload["baseline_not_executed"])
    print(payload["score_not_claimed"])
    print(payload["taxonomy_check_count"])
    print(payload["taxonomy_case_count"])
    print(payload["taxonomy_pass_count"])
    print(payload["taxonomy_failure_count"])
    print(payload["taxonomy_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["taxonomy_issue_count"])
    print(payload["warning_count"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["task_2_id"])
    print(record["source_summary"]["total_file_count"])
    print(record["source_summary"]["compatible_fixture_count"])
    print(record["source_summary"]["baseline_status"])
    print(all(result["passed"] for result in record["taxonomy_results"]))
    print(all(item["passed"] for item in record["taxonomy_gates"]))
    print(all(item["active"] is False for item in record["taxonomy_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["taxonomy_path"])
    print(payload["artifacts"]["next_actions_path"])
    print(payload["artifacts"]["interpretation_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
