from hbce_arc_agi3.milestone_11_local_solver_probe_report import (
    run_milestone_11_local_solver_probe_report_pipeline,
)


def main() -> None:
    payload = run_milestone_11_local_solver_probe_report_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_7_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_7_ready"])
    print(payload["report_created"])
    print(payload["report_section_count"])
    print(payload["coverage_layer_count"])
    print(payload["limits_count"])
    print(payload["patch_backlog_count"])
    print(payload["probe_result_count"])
    print(payload["probe_pass_count"])
    print(payload["probe_failure_count"])
    print(payload["diagnostic_only"])
    print(payload["kaggle_score_semantics"])
    print(payload["official_score_claim_allowed"])
    print(payload["competitive_score_claim_allowed"])
    print(payload["runtime_solver_modified"])
    print(payload["external_solver_dependency"])
    print(payload["primary_condition"])
    print(payload["primary_classification"])
    print(payload["solver_failure_detected"])
    print(payload["solver_probe_measured"])
    print(payload["report_check_count"])
    print(payload["report_case_count"])
    print(payload["report_case_pass_count"])
    print(payload["report_case_failure_count"])
    print(payload["report_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["report_issue_count"])
    print(payload["warning_count"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["task_6_id"])
    print(all(result["passed"] for result in record["report_case_results"]))
    print(all(item["passed"] for item in record["report_gates"]))
    print(all(item["active"] is False for item in record["report_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["coverage_path"])
    print(payload["artifacts"]["limits_path"])
    print(payload["artifacts"]["backlog_path"])
    print(payload["artifacts"]["decision_path"])
    print(payload["artifacts"]["scorecard_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
