from hbce_arc_agi3.milestone_11_local_fixture_harness_plan import (
    run_milestone_11_local_fixture_harness_plan_pipeline,
)


def main() -> None:
    payload = run_milestone_11_local_fixture_harness_plan_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_4_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_4_ready"])
    print(payload["harness_plan_created"])
    print(payload["harness_component_count"])
    print(payload["fixture_class_count"])
    print(payload["measurement_axis_count"])
    print(payload["boundary_rule_count"])
    print(payload["next_action_count"])
    print(payload["diagnostic_only"])
    print(payload["fixture_generation_performed"])
    print(payload["fixture_generation_deferred_to"])
    print(payload["official_score_claim_allowed"])
    print(payload["synthetic_fixture_score_claim_allowed"])
    print(payload["primary_condition"])
    print(payload["primary_classification"])
    print(payload["solver_failure_detected"])
    print(payload["solver_not_measured"])
    print(payload["harness_check_count"])
    print(payload["harness_case_count"])
    print(payload["harness_pass_count"])
    print(payload["harness_failure_count"])
    print(payload["harness_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["harness_issue_count"])
    print(payload["warning_count"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["task_3_id"])
    print(record["source_summary"]["primary_condition"])
    print(record["source_summary"]["primary_classification"])
    print(all(result["passed"] for result in record["harness_results"]))
    print(all(item["passed"] for item in record["harness_gates"]))
    print(all(item["active"] is False for item in record["harness_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["components_path"])
    print(payload["artifacts"]["fixture_classes_path"])
    print(payload["artifacts"]["boundary_rules_path"])
    print(payload["artifacts"]["next_actions_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
