from hbce_arc_agi3.milestone_11_solver_probe_integration import (
    run_milestone_11_solver_probe_integration_pipeline,
)


def main() -> None:
    payload = run_milestone_11_solver_probe_integration_pipeline()
    record = payload["record"]

    print(payload["status"])
    print(payload["task_status"])
    print(payload["validation_status"])
    print(payload["task_6_id"])
    print(payload["signature"])
    print(payload["baseline_commit"])
    print(payload["task_mode"])
    print(payload["task_verdict"])
    print(payload["next_stage"])
    print(payload["task_6_ready"])
    print(payload["solver_probe_contract_created"])
    print(payload["solver_probe_integration_created"])
    print(payload["probe_component_count"])
    print(payload["probe_result_count"])
    print(payload["probe_pass_count"])
    print(payload["probe_failure_count"])
    print(payload["layer_report_count"])
    print(payload["local_solver_diagnostic_measured"])
    print(payload["diagnostic_only"])
    print(payload["kaggle_score_semantics"])
    print(payload["official_score_claim_allowed"])
    print(payload["synthetic_fixture_score_claim_allowed"])
    print(payload["public_score_claim_allowed"])
    print(payload["private_score_claim_allowed"])
    print(payload["runtime_solver_modified"])
    print(payload["ranker_runtime_modified"])
    print(payload["external_solver_dependency"])
    print(payload["primary_condition"])
    print(payload["primary_classification"])
    print(payload["solver_failure_detected"])
    print(payload["solver_not_measured_from_task_5"])
    print(payload["solver_probe_measured"])
    print(payload["probe_check_count"])
    print(payload["probe_case_count"])
    print(payload["probe_case_pass_count"])
    print(payload["probe_case_failure_count"])
    print(payload["probe_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["probe_issue_count"])
    print(payload["warning_count"])
    print(payload["real_public_score_claimed"])
    print(payload["private_score_claimed"])
    print(payload["real_benchmark_score"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(record["source_summary"]["task_5_id"])
    print(all(result["passed"] for result in record["probe_case_results"]))
    print(all(item["passed"] for item in record["probe_gates"]))
    print(all(item["active"] is False for item in record["probe_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["contract_path"])
    print(payload["artifacts"]["components_path"])
    print(payload["artifacts"]["results_path"])
    print(payload["artifacts"]["layer_report_path"])
    print(payload["artifacts"]["summary_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
