from hbce_arc_agi3.milestone_10_submission_candidate_rebuild import (
    run_milestone_10_submission_candidate_rebuild_pipeline,
)


def main() -> None:
    payload = run_milestone_10_submission_candidate_rebuild_pipeline()
    rebuild = payload["rebuild"]

    print(payload["status"])
    print(payload["rebuild_status"])
    print(payload["validation_status"])
    print(payload["submission_candidate_rebuild_id"])
    print(payload["signature"])
    print(rebuild["baseline_commit"])
    print(payload["rebuild_mode"])
    print(payload["rebuild_verdict"])
    print(payload["next_allowed_stage"])
    print(payload["submission_candidate_rebuild_ready"])
    print(payload["submission_candidate_rebuild_created"])
    print(payload["local_candidate_package_rebuilt"])
    print(payload["rebuilt_candidate_payload_created"])
    print(payload["rebuilt_candidate_manifest_created"])
    print(payload["rebuilt_candidate_index_created"])
    print(payload["rebuilt_candidate_trace_created"])
    print(payload["review_handoff_created"])
    print(payload["selected_candidate_id"])
    print(payload["candidate_package_id"])
    print(payload["rebuilt_candidate_id"])
    print(payload["rebuild_component_count"])
    print(payload["rebuild_check_count"])
    print(payload["rebuild_case_count"])
    print(payload["rebuild_pass_count"])
    print(payload["rebuild_failure_count"])
    print(payload["rebuild_gate_count"])
    print(payload["passed_gate_count"])
    print(payload["rebuild_issue_count"])
    print(payload["warning_count"])
    print(payload["rebuilt_candidate_review_required_next"])
    print(payload["real_submission_candidate_created"])
    print(payload["submission_json_created"])
    print(payload["upload_package_created"])
    print(payload["real_submission_decision"])
    print(payload["real_submission_allowed"])
    print(payload["manual_upload_allowed"])
    print(payload["kaggle_authentication_allowed"])
    print(payload["kaggle_submission_sent"])
    print(payload["fail_closed_required"])
    print(payload["fail_closed_active"])
    print(rebuild["source_summary"]["rebuild_gate_id"])
    print(rebuild["source_summary"]["candidate_refresh_id"])
    print(rebuild["source_summary"]["previous_refresh_id"])
    print(all(result["passed"] for result in rebuild["rebuild_results"]))
    print(all(item["passed"] for item in rebuild["rebuild_gates"]))
    print(all(item["active"] is False for item in rebuild["rebuild_issues"]))
    print(payload["artifacts"]["json_path"])
    print(payload["artifacts"]["markdown_path"])
    print(payload["artifacts"]["manifest_path"])
    print(payload["artifacts"]["index_path"])
    print(payload["artifacts"]["payload_path"])
    print(payload["metadata"])


if __name__ == "__main__":
    main()
